# https://school.programmers.co.kr/learn/courses/30/lessons/131533
SELECT PRODUCT_CODE, SUM(SALES_AMOUNT * PRICE) AS "SALES" FROM OFFLINE_SALE os
LEFT JOIN PRODUCT p ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC