# https://school.programmers.co.kr/learn/courses/30/lessons/133026
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS "TOTAL_ORDER" FROM FIRST_HALF fh
LEFT JOIN ICECREAM_INFO ii ON fh.FLAVOR = ii.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC